//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINCOPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class AB_THERAPY
    {
        public System.Guid Id { get; set; }
        public System.Guid CRFId { get; set; }
        public System.Guid DRUGId { get; set; }
        public System.Guid ROUTEId { get; set; }
        public string SINGLE_DOSE { get; set; }
        public string FREQUENCY { get; set; }
        public string DATE_START { get; set; }
        public string DATE_END { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByDate { get; set; }
        public string UpdatedBy { get; set; }
        public string UpdatedByDate { get; set; }
        public string StateCode { get; set; }
    
        public virtual CRF CRF { get; set; }
        public virtual ROUTE ROUTE { get; set; }
        public virtual DRUG DRUG { get; set; }
    }
}
