//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINCOPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADVERSE_EVENT
    {
        public System.Guid Id { get; set; }
        public System.Guid CRFId { get; set; }
        public string NAME { get; set; }
        public System.DateTime DATE_START { get; set; }
        public System.DateTime DATE_END { get; set; }
        public string HEAVY { get; set; }
        public string RESULT { get; set; }
        public string RELATION { get; set; }
        public string ACTIONS { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByDate { get; set; }
        public string UpdatedBy { get; set; }
        public string UpdatedByDate { get; set; }
        public string StateCode { get; set; }
    
        public virtual CRF CRF { get; set; }
    }
}
