//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINCOPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANAMNESTIC_DATA_VISIT_1
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> DATE_SYMPTOM { get; set; }
        public Nullable<System.DateTime> DATE_DIAGNOSIS { get; set; }
        public Nullable<int> NUMBER_EPISODES { get; set; }
        public bool NUMBER_EPISODES_NODATA { get; set; }
        public string FUNCTION_CLASS { get; set; }
        public string OTHER_EPISODES { get; set; }
        public string SMOKE_STATUS { get; set; }
        public int SMOKE_AVERAGE { get; set; }
        public int SMOKE_YEARS { get; set; }
        public decimal SMOKE_PACK_YEARS { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByDate { get; set; }
        public string UpdatedBy { get; set; }
        public string UpdatedByDate { get; set; }
        public string StateCode { get; set; }
    
        public virtual VISIT_ONE VISIT_ONE { get; set; }
    }
}
