//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINCOPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLOOD_TESTS_FOR_MARKERS_OF_INFLAMMATION
    {
        public System.Guid Id { get; set; }
        public string VISIT_ONE_C_REACTIVE_PROTEIN { get; set; }
        public string VISIT_ONE_PROCALCITONIN { get; set; }
        public string VISIT_ONE_IL6 { get; set; }
        public string VISIT_ONE_FNO { get; set; }
        public string VISIT_TWO_C_REACTIVE_PROTEIN { get; set; }
        public string VISIT_TWO_PROCALCITONIN { get; set; }
        public string VISIT_TWO_IL6 { get; set; }
        public string VISIT_TWO_FNO { get; set; }
        public string VISIT_THREE_C_REACTIVE_PROTEIN { get; set; }
        public string VISIT_THREE_PROCALCITONIN { get; set; }
        public string VISIT_THREE_IL6 { get; set; }
        public string VISIT_THREE_FNO { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByDate { get; set; }
        public string UpdatedBy { get; set; }
        public string UpdatedByDate { get; set; }
        public string StateCode { get; set; }
    
        public virtual CRF CRF { get; set; }
    }
}
