//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINCOPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLOOD_TESTS_FOR_MARKERS_OF_CARDIAC_DYSFUNCTION
    {
        public System.Guid Id { get; set; }
        public string VISIT_ONE_BRAIN_NATRIURETIC_PEPTIDE { get; set; }
        public string VISIT_ONE_KOPEPTIN { get; set; }
        public string VISIT_ONE_PROADRENOMEDULLIN { get; set; }
        public string VISIT_TWO_BRAIN_NATRIURETIC_PEPTIDE { get; set; }
        public string VISIT_TWO_KOPEPTIN { get; set; }
        public string VISIT_TWO_PROADRENOMEDULLIN { get; set; }
        public string VISIT_THREE_BRAIN_NATRIURETIC_PEPTIDE { get; set; }
        public string VISIT_THREE_KOPEPTIN { get; set; }
        public string VISIT_THREE_PROADRENOMEDULLIN { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByDate { get; set; }
        public string UpdatedBy { get; set; }
        public string UpdatedByDate { get; set; }
        public string StateCode { get; set; }
    
        public virtual CRF CRF { get; set; }
    }
}
