//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINCOPA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CINCOPAModelContainer : DbContext
    {
        public CINCOPAModelContainer()
            : base("name=CINCOPAModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CRF> CRFSet { get; set; }
        public DbSet<WARD> WARDSet { get; set; }
        public DbSet<USERS> USERS { get; set; }
        public DbSet<VISIT_ONE> VISIT_ONESet { get; set; }
        public DbSet<VISIT_ONE_ONE> VISIT_ONE_ONESet { get; set; }
        public DbSet<VISIT_TWO> VISIT_TWOSet { get; set; }
        public DbSet<VISIT_THREE> VISIT_THREESet { get; set; }
        public DbSet<ADVERSE_EVENT> ADVERSE_EVENTSet { get; set; }
    }
}
