//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINCOPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRF
    {
        public CRF()
        {
            this.VISIT_ONE = new HashSet<VISIT_ONE>();
            this.VISIT_ONE_ONE = new HashSet<VISIT_ONE_ONE>();
            this.VISIT_TWO = new HashSet<VISIT_TWO>();
            this.VISIT_THREE = new HashSet<VISIT_THREE>();
            this.ADVERSE_EVENT = new HashSet<ADVERSE_EVENT>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid WARDId { get; set; }
        public string NAME { get; set; }
        public int NUMBER { get; set; }
        public Nullable<System.DateTime> DATE_BIRTH { get; set; }
        public Nullable<System.DateTime> DATE_HOSPITALISATION { get; set; }
        public Nullable<System.DateTime> DATE_DISCHARGE { get; set; }
        public string AE_LOGIC { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByDate { get; set; }
        public string UpdatedBy { get; set; }
        public string UpdatedByDate { get; set; }
        public string StateCode { get; set; }
    
        public virtual WARD WARD { get; set; }
        public virtual ICollection<VISIT_ONE> VISIT_ONE { get; set; }
        public virtual ICollection<VISIT_ONE_ONE> VISIT_ONE_ONE { get; set; }
        public virtual ICollection<VISIT_TWO> VISIT_TWO { get; set; }
        public virtual ICollection<VISIT_THREE> VISIT_THREE { get; set; }
        public virtual ICollection<ADVERSE_EVENT> ADVERSE_EVENT { get; set; }
    }
}
