//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINCOPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRF
    {
        public CRF()
        {
            this.ADVERSE_EVENT = new HashSet<ADVERSE_EVENT>();
            this.AB_THERAPY = new HashSet<AB_THERAPY>();
            this.MICROBIOLOGY_SPUTUM = new HashSet<MICROBIOLOGY_SPUTUM>();
            this.MICROBIOLOGY_BLOOD = new HashSet<MICROBIOLOGY_BLOOD>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid WARDId { get; set; }
        public string NAME { get; set; }
        public int NUMBER { get; set; }
        public Nullable<System.DateTime> DATE_BIRTH { get; set; }
        public Nullable<System.DateTime> DATE_HOSPITALISATION { get; set; }
        public Nullable<System.DateTime> DATE_DISCHARGE { get; set; }
        public string AE_LOGIC { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByDate { get; set; }
        public string UpdatedBy { get; set; }
        public string UpdatedByDate { get; set; }
        public string StateCode { get; set; }
    
        public virtual WARD WARD { get; set; }
        public virtual VISIT_ONE VISIT_ONE { get; set; }
        public virtual VISIT_ONE_ONE VISIT_ONE_ONE { get; set; }
        public virtual VISIT_THREE VISIT_THREE { get; set; }
        public virtual VISIT_TWO VISIT_TWO { get; set; }
        public virtual ICollection<ADVERSE_EVENT> ADVERSE_EVENT { get; set; }
        public virtual BLOOD_CLINICAL_ANALYSIS BLOOD_CLINICAL_ANALYSIS { get; set; }
        public virtual BLOOD_TESTS_FOR_MARKERS_OF_INFLAMMATION BLOOD_TESTS_FOR_MARKERS_OF_INFLAMMATION { get; set; }
        public virtual BLOOD_TESTS_FOR_MARKERS_OF_CARDIAC_DYSFUNCTION BLOOD_TESTS_FOR_MARKERS_OF_CARDIAC_DYSFUNCTION { get; set; }
        public virtual BLOOD_CHEMISTRY BLOOD_CHEMISTRY { get; set; }
        public virtual ICollection<AB_THERAPY> AB_THERAPY { get; set; }
        public virtual TEST_FOR_PNEUMOCOCCAL TEST_FOR_PNEUMOCOCCAL { get; set; }
        public virtual ICollection<MICROBIOLOGY_SPUTUM> MICROBIOLOGY_SPUTUM { get; set; }
        public virtual ICollection<MICROBIOLOGY_BLOOD> MICROBIOLOGY_BLOOD { get; set; }
    }
}
