//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINCOPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECHOCARDIOGRAPHY_VISIT_3
    {
        public System.Guid Id { get; set; }
        public System.DateTime DATE_PROCEDURE { get; set; }
        public decimal FV_PERCENT { get; set; }
        public decimal EA_LJ { get; set; }
        public decimal EA_RJ { get; set; }
        public decimal SDLA { get; set; }
        public decimal AMOUNT_OF_PERICARDIAL_EFFUSION { get; set; }
        public string COMMENTS { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByDate { get; set; }
        public string UpdatedBy { get; set; }
        public string UpdatedByDate { get; set; }
        public string StateCode { get; set; }
    
        public virtual VISIT_THREE VISIT_THREE { get; set; }
    }
}
