//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINCOPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELECTROCARDIOGRAPHY_VISIT_1
    {
        public System.Guid Id { get; set; }
        public System.DateTime DATE_PROCEDURE { get; set; }
        public bool SINUS_RHYTHM { get; set; }
        public bool ATRIAL_FIBRILLATION { get; set; }
        public bool ARRYTHMIA_SUPRAVENTRICULAR { get; set; }
        public bool ARRYTHMIA_VENTRICULAR_PREMATURE_BEATS { get; set; }
        public int HEART_RATE { get; set; }
        public string SIGNIFICANT_CHANGES { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByDate { get; set; }
        public string UpdatedBy { get; set; }
        public string UpdatedByDate { get; set; }
        public string StateCode { get; set; }
    
        public virtual VISIT_ONE VISIT_ONE { get; set; }
    }
}
