//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINCOPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MICROBIOLOGY_BLOOD
    {
        public System.Guid Id { get; set; }
        public System.Guid CRFId { get; set; }
        public string DATE_CAPTURE { get; set; }
        public string LAB_NUMBER { get; set; }
        public string GROWTH_PATHOGENS { get; set; }
        public System.Guid ORGANISMId { get; set; }
        public Nullable<System.Guid> ORGANISMId1 { get; set; }
        public string BETA { get; set; }
        public string MRSA { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByDate { get; set; }
        public string UpdatedBy { get; set; }
        public string UpdatedByDate { get; set; }
        public string StateCode { get; set; }
    
        public virtual CRF CRF { get; set; }
        public virtual ORGANISM ORGANISM { get; set; }
    }
}
