//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINCOPA
{
    using System;
    using System.Collections.Generic;
    
    public partial class XRAY_CHEST_VISIT_1
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> DATE_PROCEDURE { get; set; }
        public string PNEUMONIA_SIGNS { get; set; }
        public Nullable<bool> ALVEOLAR_INFILTRATION_RIGHT_TOP { get; set; }
        public Nullable<bool> ALVEOLAR_INFILTRATION_RIGHT_MIDDLE { get; set; }
        public Nullable<bool> ALVEOLAR_INFILTRATION_RIGHT_BOTTOM { get; set; }
        public Nullable<bool> ALVEOLAR_INFILTRATION_LEFT_TOP { get; set; }
        public Nullable<bool> ALVEOLAR_INFILTRATION_LEFT_BOTTOM { get; set; }
        public Nullable<bool> INTERSTITIAL_INFILTRATION_RIGHT_TOP { get; set; }
        public Nullable<bool> INTERSTITIAL_INFILTRATION_RIGHT_MIDDLE { get; set; }
        public Nullable<bool> INTERSTITIAL_INFILTRATION_RIGHT_BOTTOM { get; set; }
        public Nullable<bool> INTERSTITIAL_INFILTRATION_LEFT_TOP { get; set; }
        public Nullable<bool> INTERSTITIAL_INFILTRATION_LEFT_BOTTOM { get; set; }
        public Nullable<bool> PLEURAL_EFFUSION_NONE { get; set; }
        public Nullable<bool> PLEURAL_EFFUSION_RIGHT { get; set; }
        public Nullable<bool> PLEURAL_EFFUSION_LEFT { get; set; }
        public Nullable<bool> PLEURAL_EFFUSION_DOUBLE { get; set; }
        public string OTHER { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByDate { get; set; }
        public string UpdatedBy { get; set; }
        public string UpdatedByDate { get; set; }
        public string StateCode { get; set; }
    
        public virtual VISIT_ONE VISIT_ONE { get; set; }
    }
}
